### ISSUE TITLE
ANY ISSUE

### ISSUE THREAD

**Issue by spyke7** [darakhshadeepak/hacktoberfest-2022-#5]
What can I contribute?
Can I update your readme and add style
And can I add any block of code.?

**Comment by deepakstark01** [comment]
Sure can you update the contribution member

**Comment by ansh-kaushik** [comment]
@darakhshadeepak   can i contribute to it. will it we counted as an pr for hactobefest 2022

**Comment by deepakstark01** [comment]
yes

**Comment by ansh-kaushik** [comment]
thanks @darakhshadeepak  i would like to contriibute more to this
